//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        public int Id { get; set; }
        public string AnswerContent { get; set; }
        public int QuestioId { get; set; }
        public byte[] Img { get; set; }
        public Nullable<int> IdTypeWine { get; set; }
        public Nullable<int> Points { get; set; }
    
        public virtual Questionnaire Questionnaire { get; set; }
    }
}
